framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'


when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['sidi.khalifa@live.fr']
#                recipients: ['assoc.adepa@gmail.com']
